# Generated by Django 4.1.4 on 2023-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.CharField(blank=True, max_length=50, null=True)),
                ('blong_to', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
